# Generated by Django 3.2.8 on 2021-10-26 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('title', models.CharField(max_length=100)),
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('runtime', models.IntegerField()),
                ('year', models.IntegerField()),
                ('rating', models.FloatField()),
                ('directors', models.TextField()),
                ('actors', models.TextField()),
                ('certifcate', models.TextField()),
            ],
        ),
    ]
