# Generated by Django 3.2.8 on 2021-10-28 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movie_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='certifcate',
            field=models.TextField(max_length=4),
        ),
    ]
