# Generated by Django 3.2.8 on 2021-11-02 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_rename_certifcate_movie_certificate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
